name: Enrich Home Maintenance (Free Sources)

on:
  workflow_dispatch:
    inputs:
      csv_path:
        description: "Path to home_maintenance CSV"
        type: string
        default: "data/sources/home_maintenance.csv"
      sleep_sec:
        description: "Pause between rows (seconds)"
        type: number
        default: 0.8
      limit:
        description: "Process only first N rows (0 = all)"
        type: number
        default: 0
      run_ingest:
        description: "Rebuild tools.json after enrichment"
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  enrich-home-maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure these are present even if requirements.txt exists
          pip install beautifulsoup4 requests

      - name: Run enrichment (free)
        run: |
          python scripts/enrich/enrich_home_maintenance.py \
            --csv "${{ github.event.inputs.csv_path }}" \
            --sleep "${{ github.event.inputs.sleep_sec }}" \
            --limit "${{ github.event.inputs.limit }}"

      - name: Ensure Python packages (for ingest)
        if: ${{ github.event.inputs.run_ingest == 'true' }}
        run: |
          mkdir -p scripts/utils scripts/ingest
          touch scripts/__init__.py
          touch scripts/utils/__init__.py
          touch scripts/ingest/__init__.py

      - name: Build tools.json from CSV
        if: ${{ github.event.inputs.run_ingest == 'true' }}
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.ingest.csv_to_tools

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Enrich home_maintenance (free sources)${{ github.event.inputs.run_ingest == 'true' && ' & rebuild tools.json' || '' }}"
          branch: ${{ github.ref_name }}
          file_pattern: |
            data/sources/home_maintenance.csv
            data/tools.json
