name: Fetch Hotels from Google

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: "Comma-separated search keywords"
        type: string
        default: "hotel,resort,guest house,aparthotel,boutique hotel,hostel,camp"
      centers:
        description: 'Semicolon-separated "lat,lng" points'
        type: string
        # Muscat area sample points (no ellipses!)
        default: "23.611,58.471;23.585,58.407;23.620,58.280;23.600,58.545;23.560,58.640;23.570,58.420;23.520,58.385;23.640,58.520"
      radius:
        description: "Search radius (meters)"
        type: string
        default: "8000"
      basic_only:
        description: "Only core detail fields (no hours/editorial)"
        type: boolean
        default: true
      max_pages_per_query:
        description: "Max pages per (keyword,center)"
        type: string
        default: "2"
      max_places:
        description: "Stop after N unique places overall"
        type: string
        default: "150"
      details_throttle_sec:
        description: "Sleep seconds between Details calls"
        type: string
        default: "0.2"
      wall_timeout_sec:
        description: "Abort run after this many seconds"
        type: string
        default: "1200"
      no_favicons:
        description: "Do NOT set favicon URLs in logo_url"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure folders exist
        run: |
          mkdir -p data/sources
          mkdir -p assets/hotels

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run fetcher (image-free, low-cost)
        working-directory: scripts
        shell: bash
        run: |
          ARGS=()
          ARGS+=(--keywords "${{ github.event.inputs.keywords }}")
          ARGS+=(--centers "${{ github.event.inputs.centers }}")
          ARGS+=(--radius "${{ github.event.inputs.radius }}")
          ARGS+=(--max-pages-per-query "${{ github.event.inputs.max_pages_per_query }}")
          ARGS+=(--max-places "${{ github.event.inputs.max_places }}")
          ARGS+=(--details-throttle-sec "${{ github.event.inputs.details_throttle_sec }}")
          ARGS+=(--wall-timeout-sec "${{ github.event.inputs.wall_timeout_sec }}")
          if [ "${{ github.event.inputs.basic_only }}" = "true" ]; then
            ARGS+=(--basic-only)
          fi
          if [ "${{ github.event.inputs.no_favicons }}" = "true" ]; then
            ARGS+=(--no-favicons)
          fi
          echo "Running: python fetch_hotels.py ${ARGS[*]}"
          python fetch_hotels.py "${ARGS[@]}"

      - name: Build tools.json from CSV (if script exists)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          if [ -f scripts/ingest/csv_to_tools.py ] || python - <<'PY'
import importlib.util, sys, os
p = os.path.join('scripts','ingest','csv_to_tools.py')
sys.exit(0 if os.path.exists(p) else 1)
PY
          then
            python -m scripts.ingest.csv_to_tools || true
          else
            echo "csv_to_tools.py not found; skipping."
          fi

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fetch hotels and rebuild tools.json"
          branch: ${{ github.ref_name }}
          file_pattern: |
            data/sources/hotels.csv
            data/tools.json
