name: Fetch Hotels from Google

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-hotels:
    runs-on: ubuntu-latest
    env:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure folders exist
        run: |
          mkdir -p data/sources
          mkdir -p assets/hotels
          mkdir -p scripts/utils scripts/ingest
          touch scripts/__init__.py scripts/utils/__init__.py scripts/ingest/__init__.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run fetcher (image-free, low-cost; static args for now)
        working-directory: scripts
        run: |
          python fetch_hotels.py \
            --keywords "hotel,resort,guest house,aparthotel,boutique hotel,hostel,camp" \
            --centers "23.611,58.471;23.585,58.407;23.620,58.280;23.600,58.545;23.560,58.640;23.570,58.420;23.520,58.385;23.640,58.520" \
            --radius 8000 \
            --max-pages-per-query 2 \
            --max-places 150 \
            --details-throttle-sec 0.2 \
            --wall-timeout-sec 1200 \
            --basic-only \
            --no-favicons

      - name: Filter to Muscat polygon
        shell: bash
        run: |
          python - << 'PY'
import csv
from pathlib import Path

csv_path = Path("data/sources/hotels.csv")

def point_in_poly(lat, lng, poly):
    inside = False
    n = len(poly)
    for i in range(n):
        (x1, y1) = poly[i-1]     # prev vertex (lng, lat)
        (x2, y2) = poly[i]       # curr vertex (lng, lat)
        if ((y1 > lat) != (y2 > lat)):
            xinters = (x2 - x1) * (lat - y1) / (y2 - y1 + 1e-12) + x1
            if lng < xinters:
                inside = not inside
    return inside

MUSCAT_POLY = [
    (58.260, 23.655),  # NW of Al Mouj (offshore a bit)
    (58.225, 23.610),  # Seeb coast W
    (58.260, 23.560),  # Seeb inland
    (58.360, 23.540),  # Al Khoudh / Athaiba inland
    (58.430, 23.540),  # Ghubrah/Bausher inland
    (58.510, 23.520),  # Ruwi/Al Wadi Al Kabir inland
    (58.590, 23.520),  # Amerat ridge line
    (58.650, 23.560),  # Off Qantab coast (coastal)
    (58.705, 23.555),  # Yiti Beach offshore
    (58.735, 23.545),  # Shangri-La / Barr Al Jissah offshore
    (58.625, 23.575),  # Al Bustan coast
    (58.690, 23.600),  # off Muttrah coast (east)
    (58.600, 23.650),  # off Muttrah coast (north)
    (58.520, 23.640),  # off Shatti/Qurum coast
    (58.420, 23.640),  # off Athaiba/Qurum coast
    (58.340, 23.650),  # off Al Mouj coast
]

BBOX = (58.20, 58.76, 23.48, 23.70)

rows_out = []
with csv_path.open(newline="", encoding="utf-8") as f:
    rdr = csv.DictReader(f)
    fieldnames = rdr.fieldnames or []
    for r in rdr:
        try:
            lat = float((r.get("lat") or "").strip())
            lng = float((r.get("lng") or "").strip())
        except Exception:
            continue

        in_bbox = (BBOX[0] <= lng <= BBOX[1]) and (BBOX[2] <= lat <= BBOX[3])
        if not in_bbox:
            continue

        if point_in_poly(lat, lng, MUSCAT_POLY):
            rows_out.append(r)

with csv_path.open("w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    w.writerows(rows_out)

print(f"Kept {len(rows_out)} rows within Muscat polygon (incl. Al Bustan, Qantab, Yiti, Shangri-La).")
PY

      - name: Build tools.json from CSV
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m scripts.ingest.csv_to_tools

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fetch hotels (image-free), filter to Muscat, & rebuild tools.json"
          branch: ${{ github.ref_name }}
          file_pattern: |
            data/sources/hotels.csv
            data/tools.json
