name: Ingest CSV → Enrich → Build Data

on:
  workflow_dispatch:
  push:
    paths:
      - "data/sources/*.csv"
      - "scripts/**"
      - "data/schema/**"
      - "assets/**"

permissions:
  contents: write

jobs:
  build-data:
    runs-on: ubuntu-latest
    env:
      # Make the repo root importable as a package root (so 'scripts' can be imported)
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # OPTIONAL: create package markers if missing (safe to keep)
      - name: Ensure scripts is a package
        run: |
          touch scripts/__init__.py
          touch scripts/ingest/__init__.py
          touch scripts/utils/__init__.py
          touch scripts/qa/__init__.py
          touch scripts/media/__init__.py

      - name: CSV → tools.json
        run: python -m scripts.ingest.csv_to_tools

      - name: Enrich with Places/OSM/Wikidata
        run: python -m scripts.ingest.hydrate_details

      - name: Optimize images (non-blocking)
        run: python -m scripts.media.optimize_images || true

      - name: Validate schema (blocking if present)
        run: |
          if [ -f data/schema/tools.schema.json ]; then
            python -m scripts.qa.validate_schema data/tools.json data/schema/tools.schema.json
          else
            echo "No schema file; skipping"
          fi

      - name: Missing fields report (non-blocking)
        run: python -m scripts.qa.missing_fields_report || true

      - name: Commit data artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tools.json assets/images || true
          git diff --staged --quiet || git commit -m "data: update tools + images"
          git push
